import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AppProvider from "./provider";
import "./globals.css";
import GlobalMenu from "@/components/common/GlobalMenu";
import UtilityMenu from "@/components/common/UtilityMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <UtilityMenu />
          <GlobalMenu />
        <AppProvider>{children}{modal}</AppProvider>
      </body>
    </html>
  );
}
